# Generated by Django 5.0.6 on 2024-06-21 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_delete_pump'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='assigned_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_users', to='access.station'),
        ),
    ]
