# Generated by Django 5.0.6 on 2024-06-22 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
