# Generated by Django 5.0.6 on 2024-07-04 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_is_canceled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fueltype',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
