# Generated by Django 5.0.6 on 2024-07-06 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_fueltype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='fuel_types',
            field=models.ManyToManyField(related_name='stations', to='sales.fueltype'),
        ),
    ]
