# Generated by Django 5.0.6 on 2024-07-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_station_fuel_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='fuel_types',
        ),
        migrations.AddField(
            model_name='fueltype',
            name='stations',
            field=models.ManyToManyField(related_name='fuel_types', to='sales.station'),
        ),
    ]
