name: refinery_driver_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^0.13.3
  provider: ^6.0.0
  location: ^4.3.0
  web_socket_channel: ^2.0.0
  google_maps_flutter: ^2.0.6
  shared_preferences: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
