# Generated by Django 5.0.6 on 2024-06-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refinery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='current_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='plate',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
