# Generated by Django 5.0.6 on 2024-06-23 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refinery', '0002_truck_current_location_alter_truck_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='current_location',
            field=models.CharField(default='0,0', max_length=255),
        ),
    ]
