# Generated by Django 5.0.6 on 2024-06-23 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refinery', '0003_alter_truck_current_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='current_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
