# Generated by Django 5.0.6 on 2024-06-23 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refinery', '0004_alter_truck_current_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='current_location',
            field=models.CharField(default='0,0', max_length=255),
        ),
    ]
