# Generated by Django 5.0.6 on 2024-06-24 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refinery', '0007_alter_truck_current_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='in_use',
            field=models.BooleanField(default=False),
        ),
    ]
