# Generated by Django 5.0.6 on 2024-07-04 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refinery', '0010_fueltype_alter_route_fuel_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fueltype',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='fuel_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refinery.fueltype'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fuel_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refinery.fueltype'),
        ),
    ]
