# Generated by Django 5.0.6 on 2024-07-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refinery', '0014_routecheckpoint_latitude_routecheckpoint_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='routecheckpoint',
            name='route_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='routecheckpoint',
            name='station_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
